name = "backend"
compatibility_date = "2024-09-16"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODk0NThlOGUtMzUyZi00ODFlLThmZTUtYjNiNzczYjQwZDhhIiwidGVuYW50X2lkIjoiYTljZGIxNWIyZjgzM2VmNmYwYjNhM2E2ODMyMTQ4OWEzMjhmZjEyZmIyMjNmZTc3NGMxZjZlNjAyZjBjNGRmZiIsImludGVybmFsX3NlY3JldCI6IjBlYWIxNGU5LTNkNzYtNGExNC1hMTYwLWYwMGQ0YjdlZjhmYiJ9._DQMbmlgWZ14jGD-10c9Cila_IfamiZ3nlqImuqx2XQ"

JWT_SECRET = "secret_key"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"